### PR TITLE
Improve probability accuracy

### PR DESCRIPTION
**Pull request by shcabin**
Improve probability accuracy

### CODE REVIEW

**Comment by avar** [comment]
This pull request / commit messages are is/are very light on details. What was broken before, what does this fix, does this change the existing behavior for any existing hashed keys?

It doesn't make any of the existing tests fail, but your new test throws a warning:

```
$ perl -Mblib -w t/004_low_probability.t 
1..2
Use of uninitialized value in subroutine entry at /home/avar/g/Algorithm-ConsistentHash-Ketama/blib/lib/Algorithm/ConsistentHash/Ketama.pm line 30.
ok 1
ok 2
```

**Comment by dgryski** [comment]
With such a skewed distribution, I don't think ketama is the most appropriate choice. Perhaps something based on jump hash, spoca or even a deterministic random (weighted) selection using a simple biased coin flip or sometime else with the alias method.

**Comment by shcabin** [comment]
1.when the bucket is less than 1.25% probability, will never hit used .
2.There will be light changes，
sample code
$ketama->add_bucket( "node_1", 100 );
$ketama->add_bucket( "node_2", 10000-100 );
 node_1 will from 0% hit improve to 1%

**Comment by shcabin** [comment]
001-003 existing tests  also  throws same warning -_-

**Pull request closed without merging**
